/* eslint import/prefer-default-export:0 */
export const CORE_ACTIONS = {
  START: 'CORE_START',
  FAILED: 'CORE_FAILED',
  LOGOUT: 'CORE_LOGOUT',
  START_FINISHED: 'CORE_START_FINISHED',
  RESTART: 'CORE_RESTART',
  REPORT_BUG: 'CORE_REPORT_BUG',
  CHANGE_SCREEN: 'CORE_CHANGE_SCREEN',
  SEND_LOG: 'SEND_LOG',
  LOG_SENT: 'LOG_SENT',
  CLOSE_SEND_LOG_MESSAGE: 'CLOSE_SEND_LOG_MESSAGE',
  TOGGLE_DEBUG: 'TOGGLE_DEBUG',
  CLEAR_CACHE_RESTART: 'CORE_CLEAR_CACHE_RESTART',
  UI_CLEAR_CACHE_RESTART: 'CORE_UI_CLEAR_CACHE_RESTART',
};
