/* eslint import/prefer-default-export:0 */
export const CWIC_ACTIONS = {
  START_INIT: 'CWIC_START_INIT',
  INITIALIZED: 'CWIC_INITIALIZED',
  LOAD_TELEPHONE_DEVICELIST: 'CWIC_LOAD_TELEPHONE_DEVICELIST',
  SWITCH_DEVICE: 'SWITCH_TELEPHONE_DEVICE',
  LOGIN: 'CWIC_LOGIN',
  LOGOUT: 'CWIC_LOGOUT',
  SIGNED_IN: 'CWIC_SIGNED_IN',
  SIGNING_IN: 'CWIC_SIGNING_IN',
  SIGNING_OUT: 'CWIC_SIGNING_OUT',
  SIGNED_OUT: 'CWIC_SIGNED_OUT',
  INCORRECT_CREDENTIALS: 'CWIC_INCORRECT_CREDENTIALS',
};