/* eslint import/prefer-default-export:0 */
export const EVENTS_ACTIONS = {
  CONNECT: 'EVENTS_CONNECT',
  DISCONNECT: 'EVENTS_DISCONNECT',
  CONNECTED: 'EVENTS_CONNECTED',
  DISCONNECTED: 'EVENTS_DISCONNECTED',
  CONNECTION_FAILED: 'EVENTS_CONNECTION_FAILED', // This should trigger a reconnection

  RECONNECTING: 'EVENTS_RECONNECTING',
  DISCONNECTING: 'EVENTS_DISCONNECTING',

  SUBSCRIBING: 'EVENTS_SUBSCRIBING',
  SUBSCRIBED: 'EVENTS_SUBSCRIBED',
  UNSUBSCRIBED: 'EVENTS_UNSUBSCRIBED',

  EVENT_RECEIVED: 'EVENT_RECEIVED',

  ERROR: 'EVENTS_ERROR',
  FATAL_ERROR: 'EVENTS_FATAL_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};