const SYSTEM_ACTIONS = {
  CHROME_IDLE_CHANGE: 'SYSTEM_CHROME_IDLE_CHANGE',
  SAVE_RECONNECTION_STATUS: 'SYSTEM_SAVE_RECONNECTION_STATUS',
  CLEAR_SAVED_STATE: 'SYSTEM_CLEAR_SAVED_STATE',
  SYSTEM_OFFLINE: 'SYSTEM_OFFLINE',
  SYSTEM_ONLINE: 'SYSTEM_ONLINE',
};

export default SYSTEM_ACTIONS;

