
export const AUTH_STATUS = {
  NO_AUTH: 'NO_AUTH',
  START: 'START',
  ACQUIRING_AUTHTOKEN: 'ACQUIRING_AUTHTOKEN',
  AUTHTOKEN_ACQUIRED: 'AUTHTOKEN_ACQUIRED',
  AUTHTOKEN_ACQUIRE_FAILED: 'AUTHTOKEN_ACQUIRE_FAILED',
};

