export const CORE_SCREENS = {
  HOME: 'HOME',
  SETTINGS: 'SETTINGS',
};

export const CORE_STATUS = {
  STARTING: 'CORE_STARTING',
  RESTARTING: 'CORE_RESTARTING',
  CLEARING_CACHE: 'CORE_CLEARING_CACHE',
  LOGGED_OUT: 'CORE_LOGGED_OUT',
  WORKING: 'CORE_WORKING',
  FAILED: 'CORE_FAILED',
  CURRENT_SCREEN: 'CORE_CURRENT_SCREEN',
};

export const SEND_LOG_STATUS = {
  INACTIVE: 'INACTIVE',
  SENDING: 'SENDING',
  SENT: 'SENT',
};