export const CWIC_STATUS = {
  SIGNED_IN: 'CWIC_SIGNED_IN',
  SIGNING_IN: 'CWIC_SIGNING_IN',
  SIGNING_OUT: 'CWIC_SIGNING_OUT',
  SIGNED_OUT: 'CWIC_SIGNED_OUT',
  INCORRECT_CREDENTIALS: 'CWIC_INCORRECT_CREDENTIALS',
};