export const EVENTS_STATUS = {
  CONNECTING: 'CONNECTING',
  DISCONNECTING: 'DISCONNECTING',
  NOT_CONNECTED: 'NOT_CONNECTED',
  CONNECTED: 'CONNECTED',
  SUBSCRIBING: 'SUBSCRIBING',
  FAILED: 'FAILED',
  FATAL_ERROR: 'FATAL_ERROR',
};
